/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as ApiVerifyTransactionRouteImport } from './routes/api/verify-transaction'
import { Route as ApiRegisterWalletRouteImport } from './routes/api/register-wallet'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiClaimStreakRouteImport } from './routes/api/claim-streak'
import { Route as ApiCheckAccessRouteImport } from './routes/api/check-access'
import { Route as ApiBuyMovesRouteImport } from './routes/api/buy-moves'
import { Route as PlayChapterLevelRouteImport } from './routes/play.$chapter.$level'
import { Route as ApiAdminRegisteredWalletsRouteImport } from './routes/api/admin/registered-wallets'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTransactionRoute = ApiVerifyTransactionRouteImport.update({
  id: '/api/verify-transaction',
  path: '/api/verify-transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterWalletRoute = ApiRegisterWalletRouteImport.update({
  id: '/api/register-wallet',
  path: '/api/register-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaimStreakRoute = ApiClaimStreakRouteImport.update({
  id: '/api/claim-streak',
  path: '/api/claim-streak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckAccessRoute = ApiCheckAccessRouteImport.update({
  id: '/api/check-access',
  path: '/api/check-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuyMovesRoute = ApiBuyMovesRouteImport.update({
  id: '/api/buy-moves',
  path: '/api/buy-moves',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayChapterLevelRoute = PlayChapterLevelRouteImport.update({
  id: '/play/$chapter/$level',
  path: '/play/$chapter/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRegisteredWalletsRoute =
  ApiAdminRegisteredWalletsRouteImport.update({
    id: '/api/admin/registered-wallets',
    path: '/api/admin/registered-wallets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/buy-moves': typeof ApiBuyMovesRoute
  '/api/check-access': typeof ApiCheckAccessRoute
  '/api/claim-streak': typeof ApiClaimStreakRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/api/register-wallet': typeof ApiRegisterWalletRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/play/': typeof PlayIndexRoute
  '/api/admin/registered-wallets': typeof ApiAdminRegisteredWalletsRoute
  '/play/$chapter/$level': typeof PlayChapterLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/buy-moves': typeof ApiBuyMovesRoute
  '/api/check-access': typeof ApiCheckAccessRoute
  '/api/claim-streak': typeof ApiClaimStreakRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/api/register-wallet': typeof ApiRegisterWalletRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/play': typeof PlayIndexRoute
  '/api/admin/registered-wallets': typeof ApiAdminRegisteredWalletsRoute
  '/play/$chapter/$level': typeof PlayChapterLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/buy-moves': typeof ApiBuyMovesRoute
  '/api/check-access': typeof ApiCheckAccessRoute
  '/api/claim-streak': typeof ApiClaimStreakRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/api/register-wallet': typeof ApiRegisterWalletRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/play/': typeof PlayIndexRoute
  '/api/admin/registered-wallets': typeof ApiAdminRegisteredWalletsRoute
  '/play/$chapter/$level': typeof PlayChapterLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/api/buy-moves'
    | '/api/check-access'
    | '/api/claim-streak'
    | '/api/profile'
    | '/api/referrals'
    | '/api/register-wallet'
    | '/api/verify-transaction'
    | '/play/'
    | '/api/admin/registered-wallets'
    | '/play/$chapter/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/api/buy-moves'
    | '/api/check-access'
    | '/api/claim-streak'
    | '/api/profile'
    | '/api/referrals'
    | '/api/register-wallet'
    | '/api/verify-transaction'
    | '/play'
    | '/api/admin/registered-wallets'
    | '/play/$chapter/$level'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/api/buy-moves'
    | '/api/check-access'
    | '/api/claim-streak'
    | '/api/profile'
    | '/api/referrals'
    | '/api/register-wallet'
    | '/api/verify-transaction'
    | '/play/'
    | '/api/admin/registered-wallets'
    | '/play/$chapter/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ApiBuyMovesRoute: typeof ApiBuyMovesRoute
  ApiCheckAccessRoute: typeof ApiCheckAccessRoute
  ApiClaimStreakRoute: typeof ApiClaimStreakRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiReferralsRoute: typeof ApiReferralsRoute
  ApiRegisterWalletRoute: typeof ApiRegisterWalletRoute
  ApiVerifyTransactionRoute: typeof ApiVerifyTransactionRoute
  PlayIndexRoute: typeof PlayIndexRoute
  ApiAdminRegisteredWalletsRoute: typeof ApiAdminRegisteredWalletsRoute
  PlayChapterLevelRoute: typeof PlayChapterLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-transaction': {
      id: '/api/verify-transaction'
      path: '/api/verify-transaction'
      fullPath: '/api/verify-transaction'
      preLoaderRoute: typeof ApiVerifyTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register-wallet': {
      id: '/api/register-wallet'
      path: '/api/register-wallet'
      fullPath: '/api/register-wallet'
      preLoaderRoute: typeof ApiRegisterWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claim-streak': {
      id: '/api/claim-streak'
      path: '/api/claim-streak'
      fullPath: '/api/claim-streak'
      preLoaderRoute: typeof ApiClaimStreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-access': {
      id: '/api/check-access'
      path: '/api/check-access'
      fullPath: '/api/check-access'
      preLoaderRoute: typeof ApiCheckAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buy-moves': {
      id: '/api/buy-moves'
      path: '/api/buy-moves'
      fullPath: '/api/buy-moves'
      preLoaderRoute: typeof ApiBuyMovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$chapter/$level': {
      id: '/play/$chapter/$level'
      path: '/play/$chapter/$level'
      fullPath: '/play/$chapter/$level'
      preLoaderRoute: typeof PlayChapterLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/registered-wallets': {
      id: '/api/admin/registered-wallets'
      path: '/api/admin/registered-wallets'
      fullPath: '/api/admin/registered-wallets'
      preLoaderRoute: typeof ApiAdminRegisteredWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ApiBuyMovesRoute: ApiBuyMovesRoute,
  ApiCheckAccessRoute: ApiCheckAccessRoute,
  ApiClaimStreakRoute: ApiClaimStreakRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiReferralsRoute: ApiReferralsRoute,
  ApiRegisterWalletRoute: ApiRegisterWalletRoute,
  ApiVerifyTransactionRoute: ApiVerifyTransactionRoute,
  PlayIndexRoute: PlayIndexRoute,
  ApiAdminRegisteredWalletsRoute: ApiAdminRegisteredWalletsRoute,
  PlayChapterLevelRoute: PlayChapterLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
