/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as ApiVerifyTransactionRouteImport } from './routes/api/verify-transaction'
import { Route as PlayChapterLevelRouteImport } from './routes/play.$chapter.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTransactionRoute = ApiVerifyTransactionRouteImport.update({
  id: '/api/verify-transaction',
  path: '/api/verify-transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayChapterLevelRoute = PlayChapterLevelRouteImport.update({
  id: '/play/$chapter/$level',
  path: '/play/$chapter/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/play/': typeof PlayIndexRoute
  '/play/$chapter/$level': typeof PlayChapterLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/play': typeof PlayIndexRoute
  '/play/$chapter/$level': typeof PlayChapterLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/play/': typeof PlayIndexRoute
  '/play/$chapter/$level': typeof PlayChapterLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/verify-transaction'
    | '/play/'
    | '/play/$chapter/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/verify-transaction' | '/play' | '/play/$chapter/$level'
  id:
    | '__root__'
    | '/'
    | '/api/verify-transaction'
    | '/play/'
    | '/play/$chapter/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiVerifyTransactionRoute: typeof ApiVerifyTransactionRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PlayChapterLevelRoute: typeof PlayChapterLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-transaction': {
      id: '/api/verify-transaction'
      path: '/api/verify-transaction'
      fullPath: '/api/verify-transaction'
      preLoaderRoute: typeof ApiVerifyTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$chapter/$level': {
      id: '/play/$chapter/$level'
      path: '/play/$chapter/$level'
      fullPath: '/play/$chapter/$level'
      preLoaderRoute: typeof PlayChapterLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiVerifyTransactionRoute: ApiVerifyTransactionRoute,
  PlayIndexRoute: PlayIndexRoute,
  PlayChapterLevelRoute: PlayChapterLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
